apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: my-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: my-java-web-app
spec:
  params:
    - name: run-image
      value: dev.local/my-java-web-app
  source:
    git:
      url: https://github.com/sample-accelerators/my-java-web-app
      ref:
        branch: main
